spring:
  application:
    name: @project.artifactId@
  kafka:
    topic: topic-1
    bootstrap-servers: http://localhost:9092
    schema.registry.url: http://localhost:8081
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: @project.artifactId@
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mydatabase
      username: root
      password: secret
  docker:
    compose:
      enabled: false
