spring:
  application:
    name: @project.artifactId@
  kafka:
    topic: test
    bootstrap-servers: http://localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: "test-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mydb
      username: root
      password: secret
