spring:
  application:
    name: @project.artifactId@
  data:
    mongodb:
      #uri: mongodb://root:secret@localhost:27017/mydatabase?authSource=admin
      #OR (below)
      database: mydatabase
      username: root
      password: secret
      host: localhost
      port: 27017
      authentication-database: admin
  kafka:
    topic: test
    bootstrap-servers: http://localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: "true"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: "test-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
  docker:
    compose:
      enabled: false
